version: '3.8'
services:
  odoo:
    build: .
    ports:
      - "8069:8069"
    environment:
      - ODOO_DB_HOST=postgres
      - ODOO_DB_PORT=5432
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
